---
title: 'KNN Tuning'
output:
  pdf_document:
    latex_engine: xelatex
    pandoc_args:
      - '--from=markdown+hard_line_breaks'
header-includes:
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{bm}
  - \usepackage{pdfpages}
mainfont: 'Times New Roman'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  dev='png',
  dpi=128
)
```

# Dependencies

---

```{r}
for (dep in c('class', 'caret')) {
  if (!requireNamespace(dep, quietly = TRUE)) {
    install.packages(dep, dependencies = c("Depends", "Imports", "Suggests"))
  }
}

library(class)
library(caret)
```

# Preprocessing

---

### Load Data

```{r}
train <- read.csv('data/dota2Train.csv', sep=',')
test <- read.csv('data/dota2Test.csv', sep=',')
```

### Rename and Refactor

```{r}
names <- c()
for (i in 1:113) {
  names <- c(names, paste0('hero', i))
}

colnames(train) <- c('outcome', 'clusterid', 'gamemode', 'gametype', names)
colnames(test) <- c('outcome', 'clusterid', 'gamemode', 'gametype', names)

train$outcome <- ifelse(train$outcome == -1, 'loss', 'win')
train$outcome <- factor(train$outcome, levels = c('win', 'loss'))
test$outcome <- ifelse(test$outcome == -1, 'loss', 'win')
test$outcome <- factor(test$outcome, levels = c('win', 'loss'))
```

### Sample

```{r}
set.seed(42)
idx <- sample(1:nrow(train), 10000)
train <- train[idx,]
row.names(train) <- 1:nrow(train)
```

# Tuning and Training

---

```{r}
set.seed(42)
ctrl <- trainControl(method = "cv", number = 10, summaryFunction = twoClassSummary, classProbs = TRUE)
fit <- train(outcome ~ . - clusterid - gamemode - gametype, data = train, method = "knn", 
             trControl = ctrl, tuneGrid = expand.grid(k = seq(1, 100, 2)))
```

# Validation

---

### CV Results

```{r}
mat <- cbind(fit$results[,c(3,4)])
plot(mat[,1], mat[,2], type='l', lty=1,
        xlab='Sensitivity', ylab='Specificity')

k <- fit$results$k
metric <- (2 * mat[,1] * mat[,2])/ (mat[,1] + mat[,2])

pcolors <- ifelse(metric==max(metric), 'green', 'blue')
tcolors <- ifelse(metric==max(metric), 'red', 'black')
psize <- ifelse(metric==max(metric), 1.2, 0.7)
tsize <- ifelse(metric==max(metric), 1, 0.4)

points(mat[,1], mat[,2], col=pcolors, pch=19, cex=psize)
text(mat[,1], mat[,2], labels=paste0('k=',k),
     p=4, cex=tsize, col=tcolors)
```

### Best Model

```{r}
set.seed(42)
fit.best <- knn(train[,-1], test[,-1], train[,1], k=k[which.min(metric)])
```

```{r}
confusionMatrix(data = fit.best,
                reference = test[,1],
                positive = 'win')
```
